export default {
  INIT_APP: 'Initialize application',
  UPDATE_HEADER_TITLE: 'Update header title',
  ADD_PROJECT: 'Add project',
  FETCH_PROJECT: 'Fetch single project',
  FETCH_PROJECTS: 'Fetch projects',
  FETCH_IMAGES: 'Fetch images',
  UPDATE_PROJECTS: 'Update projects',
  UPDATE_PROJECT: 'Update single projects',
  UPDATE_ACTIVE_PROJECT: 'Update active project',
  UPDATE_IMAGES: 'Update images',
  UPDATE_ACTIVE_IMAGES: 'Update active images',
  CREATE_IMAGES: 'Create images',
  ADD_IMAGES: 'Add images',
  UPDATE_VIEW_VISIBILITY: 'Update view visibility',
  UPDATE_VIEW_PROPERTIES: 'Update view properties',
  UPDATE_THUMBNAILS_VIEW: 'Update thumbnails view',
  UPDATE_IMAGE_PROCESSED: 'Update image processed',
  GENERATE_OUTPUTS: 'Generate project outputs'
};